### ISSUE TITLE
[3.1.x] Backport relevant fixes from master for 3.1.5

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#1083]
Reference this issue and the cherry-picked commit id in the commit message of each backport, like so:
> `This is a backport of #1082 (commit abcd1234), as tracked in #1083`

 - [x] #1082 (only terminate executor if underlying is shut down)
 - [x] #1085 (avoid throwing / dropping errors in `create`)
 - [x] #1092 doOnSubscribe usage clarification javadoc
 - [x] #1094 groupBy code cleanup (commit titles both link to wrong PR 😞)
 - [x] 8626de2b (issue #1095) blockLast javadoc fix
 - [x] #1096 `FluxRefCount` fix
 - ...

**Comment by simonbasle** [comment]
all backports have been done
