### ISSUE TITLE
[3.1.x] Backports tracker from 3.2 to 3.1.6

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#1111]
Reference this issue and the cherry-picked commit id in the commit message of each backport, like so:
> `This is a backport of #XXXX (commit abcd1234), as tracked in #1111`

 - [x] Avoid interrupting WorkerTask Future if cancelled race.
`This is a backport of #1108 (commit a0b752a), as tracked in #1111` ✅(e8f78678)
 - [x] StepVerifier.withVirtualTime(...).verify() mutually exclusive
`This is a backport of #1104 (commit 1bd4968), as tracked in #1111` ✅(65e7d625)
 - [x] NonBlocking thread check
`This is a backport of #1109 (commit 92df4ab), as tracked in #1111` ✅(52912391)
 - [x] avoid error swallow in fromCompletionStage, onErrorDropped logs
`This is a backport of #1126 (commit 7e29da8), as tracked in #1111` ✅(97d110f3)
