### ISSUE TITLE
Switch Europium version in README from snapshot to milestone

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2142]
- [x] comment out snapshot repo
 - [x] uncomment milestone repo
 - [x] use `3.4.0-M1` instead of `-SNAPSHOT`
