### ISSUE TITLE
Epic: Context-related changes in 3.4.0

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2282]
This issue is intended to compile a list of the many `Context`-related issues that we'd like to address in 3.4.0:

 - [x] Introduce a read-only-api version of `Context`, Have `deferWithContext` and `Signal#getContext()` expose only the `ContextView` (#2279) => PR #2283 
 - [x] Deprecate `subscriberContext`, alias `subscriberContext(Context|Function)` (and have them use `ContextView`) (#2148)
 - [x] Add `transformWithContext` (which is _deferred_) (#2280)
 - (deferred to later) ~Add a way to prevent `onErrorContinue` activation to leak into the source (`scope`, #2184) => PR #2235~
 - ~Allow publishers in a chain of `CorePublisher` to influence the initial state of the `Context` at chain subscription (#2149)~

**Comment by johncfranco** [comment]
Hello, I have a context-related suggestion that might be suitable for this epic.  I've documented it in #2322 .  Could you take a look at it?
