### ISSUE TITLE
Remove 3.0.x deprecated methods, classes and interfaces in 3.1.x

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#323]
Including but not limited to these items **by `3.1.0`.`M1`**:

- [x]  `Cancellation` (see #322)
- [x]  `Scheduler#shutdown` (replaced with `Disposable#dispose()`, see #322)
- [x] make `Scheduler#dispose` default method a no-op
- [x] `Flux` `subscribe` methods with a `prefetch`
- [x] `Flux#then(Publisher<Void> other)` to be removed in favor of `thenEmpty`
- [x] `Flux#zip(Iterable)` to be removed altogether *or* replaced with a `List<Object>` returning version (see #338)
- [x] `Flux#bufferMillis` and `Flux#windowMillis` that take `long, long` as first parameters, in favor of `xxxMillisShift` aliases (see #363)
- [x] `Flux.delay` to be removed in favor of `Flux.delayElements` see #263
- [x] `Flux.window()` to be removed see #260 
- [x] `Operators.addAndGet(AtomicLong, ...)` in favor of the `AtomicLongFieldUpdater` alternative
- [x] `CancellationException` is not a singleton anymore, allowing to add suppressed exceptions to it
- [x] `xxxMillis` timed operator signatures should not be used anymore, use the Duration alternatives
- [x] `TimedScheduler` (see #451)
- [x] methods with a `delayError` parameter (see #480)
- [x] FluxSink/MonoSink `setCancellation` (see #457)
- [x] `Schedulers#timer` and `Schedulers#newTimer` (see #451)
- [x] Remove legacy introspection (see #249)
- [x] Remove static `Schedulers.decorateXxx` from public scope
- [x] `FluxSink.serialize()`
- [x] `Operators.SubscriberAdapter`
- [x] `FluxProcessor.connectXxx` -> `FluxProcessor.sink`
- [x] `Mono.then(Function)` -> `Mono.flatMap` & `Mono.flatMap` -> `Mono.flatMapMany` (see #516)
- [x] `Flux/Mono.then(Supplier), thenMany(Supplier), thenEmpty(Supplier)`.
- [x] error handling operators (`Mono.otherwiseXxx`, `Flux.switchOnError`, `Flux.onErrorResumeWith`, `mapError`) (see #535)
- [x] error Predicate or Function operators `<Throwable>` now align to `<? super Throwable>`

and **by `3.1.0`.`M2`**:
 - [x] `FluxBatch` (internal, see #484)

deprecated in `M2`, **to be removed by `3.1.0`.`M3`**:
 - [x] Most factory methods of Processors (see #471 and #616)
 - [x] `Mono#untilOther` (use `delayUntilOther(other.take(1))` instead, see #558)
 - [x] `Mono#zip(fn, iterable)` (see #619)

deprecated in `M3`, **to be removed by `3.1.0`.`RC1`**:
 - [x] Rework `Hooks.onOperator` via #775 
 - [x] Remove MutableNextSignal from public scope ( #779 )
 - [x] Make Signal interface instead of abstract class ( #779 )
 - [x] Remove Operators.checkRequest
 - [x] Replace Scheduler.REJECTED by a rejected exception from `Exceptions.failWithRejected()` (#765)
 
removed between `M3`, **and `3.1.0`.`RC1`**:
- [x] remove Mono.empty(source)
 - [x] renamed Flux.firstEmittingWith to Flux.first and Flux.firstEmittingWith to Flux.or
 - [x] `Mono#when`, `Mono#whenDelayError` (see #789)
 - [x] Current `Mono#and` to `Mono.zipWith` and `Mono.zipWhen` (see #789)
 - [x] Kotlin `whenComplete` extensions in `MonoWhenFunctions.kt`/`MonoBridges.kt` (see #789)

post RC1
- [x] changed toIterable(long prefetch) to int
- [x] changed reactor.util.lang to reactor.util.annotation
- [x] changed Operators.getAndAddCap to addCap
- [x] removed Operators.addAndGet

**Comment by simonbasle** [comment]
**List for `3.1.0`.`RELEASE`**

 - [ ] `Mono.then(Function)` (see #518 #516)

**Comment by Andrei94** [comment]
Until the branch is merged, a temporary solution would be to remove `-Werror` from 

`compileJava.options*.compilerArgs = [
		"-Xlint:serial", "-Xlint:varargs", "-Xlint:cast", "-Xlint:classfile",
		"-Xlint:dep-ann", "-Xlint:divzero", "-Xlint:empty", "-Xlint:finally",
		"-Xlint:overrides", "-Xlint:path", "-Xlint:processing", "-Xlint:static",
		"-Xlint:try", "-Xlint:fallthrough", "-Xlint:rawtypes", "-Xlint:deprecation",
		"-Xlint:unchecked", "-Xlint:-options", "-Werror"
	]`
in build.gradle

**Comment by smaldini** [comment]
Since 3.0.7 is the last 3.0.x release and all deprecated have been addressed this can be safely closed.

**Comment by simonbasle** [comment]
@smaldini I was thinking about keeping this around until GA just in case we deprecate / remove something in the meantime (which should preferably not happen, as we stabilize the API for RC1, but still...). Please reopen if you agree ;)

**Comment by smaldini** [comment]
Right added non deprecated but recently changed api which ultimately should be navigated via `API change` label too.
